<?php

	/***************************************************************
	 * Extension Manager/Repository config file for ext: "ext"
	 *
	 * Auto generated by famelo/soup 2015-11-26
	 *
	 * Manual updates:
	 * Only the data in the array - anything else is removed by next write.
	 * "version" and "dependencies" must not be touched!
	 ***************************************************************/

	$EM_CONF[$_EXTKEY] = array (
  'title' => 'Famelo Common',
  'description' => '',
  'category' => 'plugin',
  'author' => 'Marc neuhaus',
  'author_email' => 'mneuhaus@famelo.com',
  'state' => 'alpha',
  'internal' => '',
  'uploadfolder' => '1',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.0.1',
  'constraints' =>
  array (
    'depends' =>
    array (
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
);
